import { CourierRate } from './types';

export const mockCouriers: CourierRate[] = [
  {
    id: 'c1',
    name: 'Delhivery Surface',
    rating: 4.2,
    expectedDelivery: '3-5 Days',
    rate: 65,
    logoText: 'D',
    features: ['Tracking', 'Pickup'],
  },
  {
    id: 'c2',
    name: 'BlueDart Express',
    rating: 4.8,
    expectedDelivery: '1-2 Days',
    rate: 120,
    logoText: 'B',
    features: ['Fastest', 'Tracking', 'Pickup'],
  },
  {
    id: 'c3',
    name: 'Ecom Express',
    rating: 4.0,
    expectedDelivery: '4-6 Days',
    rate: 55,
    logoText: 'E',
    features: ['Tracking'],
  },
  {
    id: 'c4',
    name: 'Xpressbees',
    rating: 4.1,
    expectedDelivery: '3-4 Days',
    rate: 60,
    logoText: 'X',
    features: ['Tracking', 'Pickup'],
  },
  {
    id: 'c5',
    name: 'DTDC Lite',
    rating: 3.9,
    expectedDelivery: '5-7 Days',
    rate: 45,
    logoText: 'DT',
    features: ['Economy', 'Tracking'],
  },
  {
    id: 'c6',
    name: 'Shree Maruti',
    rating: 4.5,
    expectedDelivery: '4 Days',
    rate: 61,
    logoText: 'SM',
    features: ['Economy', 'Tracking', 'Pickup'],
  },
  {
    id: 'c7',
    name: 'Shree Maruti Air',
    rating: 4.5,
    expectedDelivery: '2 Days',
    rate: 90,
    logoText: 'SM',
    features: ['Air', 'Fast Delivery', 'Tracking', 'Pickup'],
  },
];
